({
	"createFolder": "Create Folder",
	"createFile": "Create File",
	"createLauncher": "Create Launcher",
	"application": "Application",
	"arguments": "Arguments",
	"name": "Name",
	"createFolderText": "Enter the new folder's name.",
	"createFileText": "Enter the new file's name.",
	"asFile": "As File",
	"asZip": "as ZIP (ZIP)",
	"asTgz": "as TGZ (GZIP)",
	"asTbz2": "as TBZ2 (BZIP)",
	"parentErr": "Error: Cannot move/copy a directory into itself",
	"alreadyExists": "A file with that name already exists",
	"cut": "Cut",
	"copy": "Copy",
	"paste": "Paste",
	"connFailed": "Remote Connection Failed",
	"enterPass": "Enter Password",
	"forgetImmediate": "Forget Immediately",
	"rememberForever": "Remember Forever",
	"connect": "Connect",
	"cancel": "Cancel",
	"uploading": "Uploading %s file(s)...",
	"uploadingComplete": "Upload complete",
    	"openWith": "Open With...",
	"nosuchResource": "No such resource! Check the path and try again.",
	"permissionDenied": "You do not have permission to access this resource.",
	"unknownError": "An unknown error occured while trying to access the resource."
})
